# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-action


name: run cypress tests and upload test artifacts
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0,30 * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    name: run cypress tests and generate report
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        continue-on-error: true
      # with:
      # record: true
      # env:
      # CYPRESS_RECORD_KEY: ${{ secrets.RECORDING_KEY }}

      # - name: Print Dashboard URL
      #   run: |
      #   echo Cypress finished with: ${{ steps.cypress.outcome }}
      #   echo See results at ${{ steps.cypress.outputs.dashboardUrl }}   

      - name: generate cucumber test report
        run: npm run cucumber-report

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cucumber-report
          path: reports
    

 

      

 - name: Cypress tests
  uses: cypress-io/github-action@v2
  # let's give this action an ID so we can refer
  # to its output values later
  id: cypress
  # Continue the build in case of an error, as we need to set the
  # commit status in the next step, both in case of success and failure
  continue-on-error: true
  with:
    record: true
  env:
    CYPRESS_RECORD_KEY: ${{ secrets.RECORDING_KEY }}
- name: Print Dashboard URL
  run: |
    echo Cypress finished with: ${{ steps.cypress.outcome }}
    echo See results at ${{ steps.cypress.outputs.dashboardUrl }}         