# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-action


name: run cypress tests and upload test artifacts
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0,30 * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    name: run cypress tests and generate report
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder


      # to always have something to upload


      - name: generate cucumber test report
        run: npm run cucumber-report

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cucumber-report
          path: reports
    

 

      

          